### ISSUE TITLE
Installation and usage instructions

### ISSUE THREAD

**Issue by jkorstia** [ekmolloy/phylotools#1]
Hi Erin,

I am trying to follow the methods from the Springer et al. 2020 Heredity paper with some retrotransposon data.  Unfortunately, I have been unable to figure out how to correctly use your script to convert my phylip formatted presence/absence matrix.  I was able to run make on the makefile, but only after changing the "G++" in line 1 to "g++".  When I try to run the executable, it seems to read in my data, but no output files are produced (see below).  My matrix does not have any missing data.

 ./run_binary_character_matrix_to_newick ves_phylip_21apr21.txt > ves_newick_incomplete_out
Read character matrix in 0.00237467 seconds
Wrote newick strings in 3.164e-06 seconds

I would really appreciate it if you could help me figure out where I am going wrong here.  Please let me know if there is any additional information I can provide that may be helpful.

Thanks,
Jenny

**Comment by ekmolloy** [comment]
Hi Jenny, Thanks for your message - I am looking into this issue. -Erin

**Comment by ekmolloy** [comment]
Hi Jenny, could you let me know whether your input file is in phylip or fast format? It would be great if you could provide the first few (six-ish) lines of the file, so I could test how things are working on my end. You could post them here or email them to ekmolloy@umd.edu. Thanks! -Erin

**Comment by ekmolloy** [comment]
We resolved the issue by editing the newline characters of the input file, so that `\n` was used instead of `\r`. I have now added a README file to the repository with this information!
